### ISSUE TITLE
Error in robot.launch

### ISSUE THREAD

**Issue by usman2k** [dietriro/robotino-ros#3]
I am using ROS Noetic and built the "rto_core" package successfully.
But I am running "src/rto_core/rto_bringup/launch/robot.launch", then I am geting following:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/__init__.py", line 347, in main
    p.start()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 305, in start
    self._start_infrastructure()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 254, in _start_infrastructure
    self._load_config()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 156, in _load_config
    self.config = roslaunch.config.load_config_default(self.roslaunch_files, self.port,
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 633, in _include_tag
    self._recurse_load(ros_config, launch.childNodes, child_ns, \
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 633, in _include_tag
    self._recurse_load(ros_config, launch.childNodes, child_ns, \
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 679, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 271, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/loader.py", line 478, in param_value
    with open(textfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/catkin_ws/src/rto_core/rto_description/urdf/robots/rto-1.urdf'

**Comment by mishra-neha** [comment]
Please change in ~/catkin_ws/src/rto_core/rto_bringup/launch/components/base.xml 
 file (line 11)

 <param name="robot_description" textfile="$(find rto_description)/urdf/robots/**$(arg robot).urdf"** /> 

to

 <param name="robot_description" textfile="$(find rto_description)/urdf/robots/**$(arg robot).urdf.xacro"** />. 

Hope it helps.

**Comment by mishra-neha** [comment]
Please change in **~/catkin_ws/src/rto_core/rto_bringup/launch/components/base.xml**  file (line 11)

 `<param name="robot_description" textfile="$(find rto_description)/urdf/robots/$(arg robot).urdf" /> ` 

to 

 `<param name="robot_description" textfile="$(find rto_description)/urdf/robots/$(arg robot).urdf.xacro" />`


Hope it helps.

**Comment by usman2k** [comment]
Thanks, It's work.
